### PR TITLE
Run tests with Julia 1.3

### PR DESCRIPTION
**Pull request by tkf**

### CODE REVIEW

**Comment by tkf** [comment]
(I added `no changelog` label so that TagBot will ignore it when creating the release note)

**Comment by DilumAluthge** [comment]
I also added "1" to the list, which always points to the latest stable release of Julia 1.x.

**Comment by tkf** [comment]
Ah, I didn't know that `1` can be used for that. Thanks, it's good to know!

I guess not adding `- "1.3"` for now also makes sense but (presumably) we'll have 1.4 soon so I guess it doesn't matter.

**Comment by DilumAluthge** [comment]
Yeah since 1.4 will be out soon, might as well keep 1.3 in the list.

If you can ping me once all CI is passing, I can merge.

**Comment by tkf** [comment]
Thanks for reviewing and merging this!  BTW, @KristofferC  gave me the merge privilege so I can merge things myself (if someone approved the PR).

**Pull request merged**
